//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Pushs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PushResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PushResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Pushs.PushResources", typeof(PushResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string DelegateAcceptedRequestMessage_BR {
            get {
                return ResourceManager.GetString("DelegateAcceptedRequestMessage_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string DelegateAcceptedRequestMessage_EN {
            get {
                return ResourceManager.GetString("DelegateAcceptedRequestMessage_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string DelegateAcceptedRequestMessage_ES {
            get {
                return ResourceManager.GetString("DelegateAcceptedRequestMessage_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string DelegateInactivityMessage_BR {
            get {
                return ResourceManager.GetString("DelegateInactivityMessage_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string DelegateInactivityMessage_EN {
            get {
                return ResourceManager.GetString("DelegateInactivityMessage_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string DelegateInactivityMessage_ES {
            get {
                return ResourceManager.GetString("DelegateInactivityMessage_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string DelegateRegisterNewRequestMessage_BR {
            get {
                return ResourceManager.GetString("DelegateRegisterNewRequestMessage_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        internal static string DelegateRegisterNewRequestMessage_EN {
            get {
                return ResourceManager.GetString("DelegateRegisterNewRequestMessage_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string DelegateRegisterNewRequestMessage_ES {
            get {
                return ResourceManager.GetString("DelegateRegisterNewRequestMessage_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string DelegateRejectedRequestMessage_BR {
            get {
                return ResourceManager.GetString("DelegateRejectedRequestMessage_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        internal static string DelegateRejectedRequestMessage_EN {
            get {
                return ResourceManager.GetString("DelegateRejectedRequestMessage_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string DelegateRejectedRequestMessage_ES {
            get {
                return ResourceManager.GetString("DelegateRejectedRequestMessage_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova notificação !.
        /// </summary>
        internal static string Notification_BR {
            get {
                return ResourceManager.GetString("Notification_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New notification!.
        /// </summary>
        internal static string Notification_EN {
            get {
                return ResourceManager.GetString("Notification_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva notificacion!.
        /// </summary>
        internal static string Notification_ES {
            get {
                return ResourceManager.GetString("Notification_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string TeamMemberInactivityMessage_BR {
            get {
                return ResourceManager.GetString("TeamMemberInactivityMessage_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        internal static string TeamMemberInactivityMessage_EN {
            get {
                return ResourceManager.GetString("TeamMemberInactivityMessage_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string TeamMemberInactivityMessage_ES {
            get {
                return ResourceManager.GetString("TeamMemberInactivityMessage_ES", resourceCulture);
            }
        }
    }
}
